### ISSUE TITLE
Publish new release supporting Jellyfin 10.10

### ISSUE THREAD

**Issue by 3flex** [jellyfin/jellyfin-sdk-typescript#817]
Hi there, it would be great to get a new release supporting the API updates in Jellyfin 10.10, and also review the min supported Jellyfin API version (does it also need a bump to 10.10? I'm not sure if the changes are backwards compatible.)

Ideally going forward the TS SDK release would be included in the overall Jellyfin release process so the SDK is kept up to date with major releases.

Thanks!

**Comment by 3flex** [comment]
Sorry I probably jumped the gun a bit here, I can see this is currently being worked on.

**Comment by thornbill** [comment]
Yes this is in the works. An update will probably be published tomorrow.

We can't publish an sdk update prior to the server release because we depend on a stable API spec being available to generate the code. We are discussing done changes to the release process for the future that might change this though.

**Comment by 3flex** [comment]
Updates to release processes relates to my comment here too: https://github.com/jellyfin/jellyfin-chromecast/pull/650#issuecomment-2440221002

**Comment by thornbill** [comment]
A new release has been published: https://github.com/jellyfin/jellyfin-sdk-typescript/releases/tag/v0.11.0
